return {
  -- You can also add new plugins here as well:
  -- Add plugins, the lazy syntax
  -- "andweeb/presence.nvim",
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "BufRead",
  --   config = function()
  --     require("lsp_signature").setup()
  --   end,
  -- },
  -- {
  --   "barrett-ruth/live-server.nvim",
  --   build = "yarn global add live-server",
  --   opts = {},
  -- },
  -- {
  --   "turbio/bracey.vim",
  --   event = "User AstroFile",
  --   lazy = false,
  -- },
}
